### ISSUE TITLE
Question about FnScopes and shadowed variables

### ISSUE THREAD

**Issue by kjeremy** [matklad/rust-analyzer#97]
I would expect the following to have two scopes named `x`. Is that correct?

```rust
fn foo(x: String) {
    let x : &str = &x<|>;
}
```

**Comment by kjeremy** [comment]
As in the `x` of `x: String` or the `let x ...` ?

**Comment by matklad** [comment]
The `let x` one.

**Comment by matklad** [comment]
oh, now, sorrry, I am 100% wrong of course

**Comment by matklad** [comment]
Of course `x` from `let x` shouldn't be visible in the expression after `=`. If it is visible, then it's the bug in the implementation.

**Comment by kjeremy** [comment]
Ahhh thanks. that makes sense.
